# the language file to be used
# file paths are relative to ${plugin_dir}/bukkit_lang
language: en_us.lang

# verbosity settings for regulating when VoxelVert prints debug information
verbosity:
  enable: true
  disable: true
  runtime: true

# settings for the HTTP-server which allows for downloading files from the inventory directly
http:
  # enables or disables the HTTP-server (true|false)
  #
  # default = true
  enable: true

  # specifies the port on which the HTTP-server runs
  #
  # default = 26000
  port: 26000

  # http host with placeholders
  # you can replace $localhost with the domain name of your server if you have one
  # you can omit $port if you are hosting on port 80, as this is the default HTTP port
  # NOTE: you might need to run VoxelVert with administrator permissions to bind to port 1024 and below on Linux)
  # NOTE: you must replace $localhost with your domain to allow Minecraft clients to open links by clicking in-game
  #   EXAMPLE: "my-server.net:$port"
  #   by default, VoxelVert uses http://checkip.amazonaws.com/ to check your server's IP so that you can download and
  #   upload files without a domain
  #
  # $localhost = your public IP-address
  # $port = the port on which your HTTP-server runs
  # default = "$localhost:$port"
  host: "$localhost:$port"

  # download path for file downloads
  #
  # default = "/vv/dl"
  download_path: "/vv/dl"

  # upload path for file uploads
  #
  # default = /vv/up
  upload_path: "/vv/up"

# limitation settings (upload file sizes, conversion file sizes etc.)
# NOTE: values must be provided in the format:
#
#           { }<number>{ }<unit>
#
#       { } is optional whitespace
#       <number> number is a decimal number
#       <unit> is a unit such as KB, KiB, MB, MiB, etc. (case insensitive)
file_limits:

  # limits for default players
  # default = 100KiB
  default:
    format:
      image: "4 MiB"
      model: 4 MiB
      qef: 4 MiB
      qb: 1 MiB
      stl: 1 MiB
      wavefront: 4 MiB
      schematic: 1 MiB
    download: 10 MiB
    upload: 4 MiB

  # limits for operators
  # default = 1MiB
  op:
    format:
      image: 40 MiB
      model: 40 MiB
      qef: 40 MiB
      qb: 10 MiB
      stl: 10 MiB
      wavefront: 40 MiB
      schematic: 10 MiB
    download: 100 MiB
    upload: 40 MiB
