# the language file to be used
# file paths are relative to ${plugin_dir}/bukkit_lang
language: en_us.lang

# verbosity settings for regulating when VoxelVert prints debug information
verbosity:
  enable: true
  disable: true
  runtime: true
