name: VoxelVert
main: eisenwave.vv.bukkit.VoxelVertPlugin
version: R1.5
api-version: 1.13
author: Eisenwave
softdepend: [WorldEdit]

permissions:
  vv.command.convert:
    description: use command /convert
    default: op
  vv.command.probe-block:
    description: use command /probe-block
    default: op
  vv.command.voxelvert:
    description: use command /voxelvert
    default: op
  vv.command.voxelvert-list:
    description: use command /voxelvert-list
    default: op
  vv.command.voxelvert-remove:
    description: use command /voxelvert-remove
    default: op
  vv.command.voxelvert-move:
    description: use command /voxelvert-move
    default: op
  vv.command.voxelvert-share:
    description: use command /voxelvert-share
    default: op
  vv.admin.converter:
    description: command options related to converter thread
    default: op
  vv.admin.reload:
    description: reload the plugin
    default: op
  vv.admin.status:
    description: get the status of the plugin
    default: op
  vv.admin.version:
    description: get the version of the plugin
    default: op
  vv.share.worldedit:
    description: share schematic files with the server's WorldEdit folder
    default: true
  vv.share.player:
    description: share files with another player
    default: true
  vv.download:
    description: download files
    default: true
  vv.upload:
    description: upload files
    default: true

commands:
  convert:
    permission: vv.command.convert
    aliases: [c]
    description: convert files
  probe-block:
    permission: vv.command.proble-block
    description: probe information about looked at block
  voxelvert:
    permission: vv.command.voxelvert
    aliases: [vv]
    description: configuration/stats command
  voxelvert-remove:
    permission: vv.command.voxelvert-remove
    aliases: [vv-rm]
    description: remove a file
  voxelvert-move:
    permission: vv.command.voxelvert-move
    aliases: [vv-mv]
    description: move a file
  voxelvert-copy:
    permission: vv.command.voxelvert-copy
    aliases: [vv-cp]
    description: copy a file
  voxelvert-list:
    permission: vv.command.voxelvert-list
    aliases: [vv-ls]
    description: list files
  voxelvert-share:
    permission: vv.command.voxelvert-share
    aliases: [vv-share]
    description: share a file

  invtest:
    usage: "\u00A7cUsage: /invtest"
    permission: eisen.inv.invtest
  cancelquery:
    usage: "\u00A7cUsage: /cancelquery"
    permission: eisen.inv.cancelquery
