name: VoxelVert
main: org.eisenwave.vv.bukkit.VoxelVertPlugin
version: 0.1
author: Eisenwave
depend: [WorldEdit]
softdepend: [BulktEdit]

permissions:
  vv.cmd.convert:
    default: op
  vv.cmd.voxelvert:
    default: op
  vv.cmd.voxelvert-list:
    default: op
  vv.cmd.voxelvert-remove:
    default: op
  vv.cmd.voxelvert-move:
    default: op
  vv.cmd.vvadmin:
    default: op

commands:
  convert:
    permission: vv.cmd.convert
    aliases: [c]
    description: convert files
  voxelvert:
    permission: vv.cmd.voxelvert
    aliases: [vv]
    description: configuration/stats command

  voxelvert-remove:
    permission: vv.cmd.voxelvert-remove
    aliases: [vv-rm]
    description: remove a file
  voxelvert-move:
    permission: vv.cmd.voxelvert-move
    aliases: [vv-mv]
    description: move a file
  voxelvert-copy:
    permission: vv.cmd.voxelvert-copy
    aliases: [vv-cp]
    description: copy a file
  voxelvert-list:
    permission: vv.cmd.voxelvert-list
    aliases: [vv-ls]
    description: list files
